name: Update README with latest blog posts

on:
  schedule:
    - cron: '1 0/6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch and update README
        run: |
          # Fetch blog JSON
          curl -s https://blog.vishaldhatrika.me/api/posts > posts.json

          # Prepare markdown list (top 5 posts)
          echo "<!-- BLOG-POST-LIST:START -->" > blog_section.md
          jq -r '.[0:5][] | "- [\(.title)](\(.url))"' posts.json >> blog_section.md
          echo "<!-- BLOG-POST-LIST:END -->" >> blog_section.md

          # Replace old section in README
          awk '
            BEGIN { start=0 }
            /<!-- BLOG-POST-LIST:START -->/ { print; start=1; while (getline < "blog_section.md") print; next }
            /<!-- BLOG-POST-LIST:END -->/ { start=0; next }
            start == 0 { print }
          ' README.md > new_README.md

          mv new_README.md README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "📚 Update latest blog posts" || echo "No changes to commit"
          git push
